<?php

/**
 * @file
 * E.
 *
 * When enabled, multiple languages can be added. The site interface can be
 * displayed in different languages, and nodes can have languages assigned. The
 * setup of languages and translations is completely web based. Gettext portable
 * object files are supported.
 */

/**
 * Implements hook_form_FORM_ID_alter() for language_admin_add_form().
 */
function test_lang_form_language_admin_add_form_alter(&$form, FormStateInterface $form_state) {
  $i = 10;
  $i += 20;
}
