<?php

/**
 * @file
 * Contains cgov_event.install.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function cgov_general_install() {
  // Get our helper.
  $siteHelper = \Drupal::service('cgov_core.tools');

  // Add content type permissions.
  $siteHelper->addContentTypePermissions('cgov_general', ['content_author']);
  $siteHelper->attachContentTypeToWorkflow('cgov_general', 'editorial_workflow');

}
