<?php

/**
 * @file
 * Contains cgov_application_page.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function cgov_application_page_node_insert(EntityInterface $entity) {
  if ($entity->bundle() === 'cgov_application_page') {
    /* New entity then the app path never existed. Register.
     */
    $app_path_svc = \Drupal::service('app_module.app_path_manager');
    $app_path_svc->registerAppPath($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function cgov_application_page_node_update(EntityInterface $entity) {
  if ($entity->bundle() === 'cgov_application_page') {
    /* Update the app path information, or create if it did not exist
     * before.
     */
    $app_path_svc = \Drupal::service('app_module.app_path_manager');
    $app_path_svc->updateAppPathData($entity);
  }
}
